# Generated by Django 4.2.16 on 2024-11-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
