# Generated by Django 4.2.16 on 2024-11-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_image'),
        ('seasonality', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='products', to='badges.badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonality',
            field=models.ManyToManyField(blank=True, related_name='products', to='seasonality.season'),
        ),
    ]
